events {
    worker_connections 1024;
}

http {

    upstream auth-service {
        server auth:8081;
    }

    upstream report-service {
        server report:8082;
    }

    upstream notifications-service{
        server notifications-service:8083;
    }

    server {
        listen 80;

        location /api/register {
            proxy_pass http://auth-service/api/register;
            proxy_set_header Content-Type application/json;
            proxy_set_header Host $host;
        }

        location /api/login {
            proxy_pass http://auth-service/api/login;
            proxy_set_header Content-Type application/json;
            proxy_set_header Host $host;
        }

        location = /_validate_token {
                    internal;
                    proxy_method POST;
                    proxy_pass http://auth-service/api/validate-token;
                    proxy_connect_timeout 5s;
                    proxy_read_timeout 20s;
                    proxy_send_timeout 20s;
                    proxy_set_header Authorization $http_authorization;
                    proxy_set_header Host $host;
                    proxy_pass_request_body off;
                    proxy_set_header Content-Length "";
        }

        location ~ ^/api/send/(?<template_id>\d+) {
            auth_request /_validate_token;
            auth_request_set $user_id $upstream_http_grpc_metadata_x_user_id;
            auth_request_set $auth_status $upstream_status;
            proxy_pass http://notifications-service;
            proxy_set_header Host $host;
            proxy_set_header X-User-ID $user_id;
            proxy_set_header TE trailers;
            proxy_http_version 1.1;
            proxy_set_header Content-Type application/json;

            error_page 401 = @error401;
            error_page 403 = @error403;
        }

        location /api {
            auth_request /_validate_token;
            auth_request_set $user_id $upstream_http_grpc_metadata_x_user_id;
            auth_request_set $auth_status $upstream_status;
            proxy_pass http://report-service;
            proxy_set_header Host $host;
            proxy_set_header X-User-ID $user_id;
            proxy_set_header TE trailers;
            proxy_http_version 1.1;
            proxy_set_header Content-Type application/json;

            error_page 401 = @error401;
            error_page 403 = @error403;
        }

       location @error401 {
           add_header Content-Type application/json;
           return 401 '{"error": "Unauthorized", "message": "Invalid or missing token"}';
       }

       location @error403 {
           add_header Content-Type application/json;
           return 403 '{"error": "Forbidden", "message": "Insufficient permissions"}';
       }
    }
}