// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	report "report/pkg/api/report"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddContactsToTemplate mocks base method.
func (m *MockRepository) AddContactsToTemplate(ctx context.Context, templateId int64, contactIds []int64, userId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContactsToTemplate", ctx, templateId, contactIds, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContactsToTemplate indicates an expected call of AddContactsToTemplate.
func (mr *MockRepositoryMockRecorder) AddContactsToTemplate(ctx, templateId, contactIds, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContactsToTemplate", reflect.TypeOf((*MockRepository)(nil).AddContactsToTemplate), ctx, templateId, contactIds, userId)
}

// CreateContact mocks base method.
func (m *MockRepository) CreateContact(ctx context.Context, c *report.Contact, userId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, c, userId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockRepositoryMockRecorder) CreateContact(ctx, c, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockRepository)(nil).CreateContact), ctx, c, userId)
}

// CreateTemplate mocks base method.
func (m *MockRepository) CreateTemplate(ctx context.Context, t *report.Template, userId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, t, userId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockRepositoryMockRecorder) CreateTemplate(ctx, t, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockRepository)(nil).CreateTemplate), ctx, t, userId)
}

// DeleteContact mocks base method.
func (m *MockRepository) DeleteContact(ctx context.Context, contactId, userId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, contactId, userId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockRepositoryMockRecorder) DeleteContact(ctx, contactId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockRepository)(nil).DeleteContact), ctx, contactId, userId)
}

// DeleteTemplate mocks base method.
func (m *MockRepository) DeleteTemplate(ctx context.Context, templateId, userId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, templateId, userId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockRepositoryMockRecorder) DeleteTemplate(ctx, templateId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockRepository)(nil).DeleteTemplate), ctx, templateId, userId)
}

// GetContact mocks base method.
func (m *MockRepository) GetContact(ctx context.Context, contactId, userId int64) (*report.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", ctx, contactId, userId)
	ret0, _ := ret[0].(*report.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockRepositoryMockRecorder) GetContact(ctx, contactId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockRepository)(nil).GetContact), ctx, contactId, userId)
}

// GetContacts mocks base method.
func (m *MockRepository) GetContacts(ctx context.Context, userId int64) ([]*report.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContacts", ctx, userId)
	ret0, _ := ret[0].([]*report.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockRepositoryMockRecorder) GetContacts(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockRepository)(nil).GetContacts), ctx, userId)
}

// GetContactsByTemplate mocks base method.
func (m *MockRepository) GetContactsByTemplate(ctx context.Context, templateId, userId int64) ([]*report.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactsByTemplate", ctx, templateId, userId)
	ret0, _ := ret[0].([]*report.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactsByTemplate indicates an expected call of GetContactsByTemplate.
func (mr *MockRepositoryMockRecorder) GetContactsByTemplate(ctx, templateId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactsByTemplate", reflect.TypeOf((*MockRepository)(nil).GetContactsByTemplate), ctx, templateId, userId)
}

// GetTemplate mocks base method.
func (m *MockRepository) GetTemplate(ctx context.Context, templateId, userId int64) (*report.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, templateId, userId)
	ret0, _ := ret[0].(*report.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockRepositoryMockRecorder) GetTemplate(ctx, templateId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockRepository)(nil).GetTemplate), ctx, templateId, userId)
}

// ListTemplates mocks base method.
func (m *MockRepository) ListTemplates(ctx context.Context, userId int64) ([]*report.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx, userId)
	ret0, _ := ret[0].([]*report.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockRepositoryMockRecorder) ListTemplates(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockRepository)(nil).ListTemplates), ctx, userId)
}

// UpdateContact mocks base method.
func (m *MockRepository) UpdateContact(ctx context.Context, c *report.Contact, userId int64) (*report.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, c, userId)
	ret0, _ := ret[0].(*report.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockRepositoryMockRecorder) UpdateContact(ctx, c, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockRepository)(nil).UpdateContact), ctx, c, userId)
}

// UpdateTemplate mocks base method.
func (m *MockRepository) UpdateTemplate(ctx context.Context, t *report.Template, userId int64) (*report.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, t, userId)
	ret0, _ := ret[0].(*report.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockRepositoryMockRecorder) UpdateTemplate(ctx, t, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockRepository)(nil).UpdateTemplate), ctx, t, userId)
}
